/**
 * Zona DNS BIND (RFC 1035) orientada a Hostinger hPanel y paneles similares.
 *
 * Hostinger: Export/Import .txt — ver
 * https://www.hostinger.com/support/1583249-how-to-manage-dns-records-at-hostinger/
 *
 * El preview de Hostinger a menudo responde "Not Found" si falta SOA/NS o si
 * el TXT DKIM va partido en varias comillas. Por eso incluimos SOA+NS de
 * dns-parking (defaults Hostinger) y DKIM en una sola cadena entrecomillada.
 */

export type ZoneDnsRecord = {
  type: 'TXT' | 'CNAME' | 'MX' | string;
  host: string;
  value: string;
  priority?: number | null;
};

/** TTL por defecto en Hostinger. */
const DEFAULT_TTL = 14400;

/** Nameservers por defecto de Hostinger (dns-parking). */
const HOSTINGER_NS = ['ns1.dns-parking.com.', 'ns2.dns-parking.com.'] as const;

function ensureFqdn(hostname: string): string {
  const h = hostname.trim().replace(/\.$/, '');
  return `${h}.`;
}

/** Nombre relativo a $ORIGIN (@, subdominio). */
export function toRelativeOwner(host: string, apex: string): string {
  const h = host.trim().replace(/\.$/, '').toLowerCase();
  const root = apex.trim().replace(/\.$/, '').toLowerCase();
  if (!h || h === '@' || h === root) return '@';
  const suffix = `.${root}`;
  if (h.endsWith(suffix)) {
    const relative = h.slice(0, -suffix.length);
    return relative || '@';
  }
  return h;
}

function escapeTxt(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function stripOuterQuotes(value: string): string {
  let raw = value.trim().replace(/[\r\n]+/g, '');
  if (raw.startsWith('"') && raw.endsWith('"') && raw.length >= 2) {
    raw = raw.slice(1, -1);
  }
  return raw;
}

/**
 * TXT en UNA sola cadena entrecomillada.
 * Hostinger falla el preview con varios "chunk" "chunk" en la misma línea.
 */
export function formatTxtRdata(value: string): string {
  return `"${escapeTxt(stripOuterQuotes(value))}"`;
}

function typeOrder(type: string): number {
  switch (type.toUpperCase()) {
    case 'TXT':
      return 1;
    case 'MX':
      return 2;
    case 'CNAME':
      return 3;
    default:
      return 9;
  }
}

function serialYyyymmdd(): number {
  const d = new Date();
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, '0');
  const day = String(d.getUTCDate()).padStart(2, '0');
  return Number(`${y}${m}${day}01`);
}

function formatRecordLine(record: ZoneDnsRecord, apex: string, ttl: number): string {
  const owner = toRelativeOwner(record.host, apex);
  const type = record.type.toUpperCase();

  // Tabs como en exports típicos de Hostinger / BIND
  if (type === 'MX') {
    const prio = record.priority ?? 10;
    return `${owner}\t${ttl}\tIN\tMX\t${prio}\t${ensureFqdn(record.value)}`;
  }
  if (type === 'CNAME') {
    return `${owner}\t${ttl}\tIN\tCNAME\t${ensureFqdn(record.value)}`;
  }
  if (type === 'TXT') {
    return `${owner}\t${ttl}\tIN\tTXT\t${formatTxtRdata(record.value)}`;
  }
  return `${owner}\t${ttl}\tIN\t${type}\t${record.value}`;
}

export type BindZoneOptions = {
  ttl?: number;
  /** Incluir SOA+NS (recomendado para preview Hostinger). Default true. */
  includeSoaNs?: boolean;
  nameservers?: string[];
  comment?: string;
};

/** Contenido .txt BIND compatible con Hostinger Import. */
export function buildBindZoneFile(
  apex: string,
  records: ZoneDnsRecord[],
  opts?: BindZoneOptions,
): string {
  const root = apex.trim().replace(/\.$/, '').toLowerCase();
  const ttl = opts?.ttl ?? DEFAULT_TTL;
  const includeSoaNs = opts?.includeSoaNs !== false;
  const nameservers = (opts?.nameservers?.length ? opts.nameservers : [...HOSTINGER_NS]).map(
    (ns) => ensureFqdn(ns),
  );
  const primaryNs = nameservers[0] ?? HOSTINGER_NS[0];

  const sorted = [...records].sort((a, b) => {
    const td = typeOrder(a.type) - typeOrder(b.type);
    if (td !== 0) return td;
    return toRelativeOwner(a.host, root).localeCompare(toRelativeOwner(b.host, root));
  });

  const lines: string[] = [
    `; Zone file for ${root}`,
    `; Generated by MatuMailer for Hostinger / BIND RFC 1035`,
    `; ${new Date().toISOString()}`,
    opts?.comment ? `; ${opts.comment}` : null,
    `; Import tip: leave "Replace existing records" UNCHECKED (Append).`,
    `$TTL ${ttl}`,
    `$ORIGIN ${root}.`,
  ].filter((l): l is string => l !== null);

  if (includeSoaNs) {
    // SOA multilinea: muchos paneles (Hostinger) lo exigen para poder previsualizar.
    lines.push(
      `@\tIN\tSOA\t${primaryNs} root.${root}. (`,
      `\t\t\t\t${serialYyyymmdd()} ; serial`,
      `\t\t\t\t3600 ; refresh`,
      `\t\t\t\t7200 ; retry`,
      `\t\t\t\t1209600 ; expire`,
      `\t\t\t\t${ttl} ; minimum`,
      `\t\t\t\t)`,
    );
    for (const ns of nameservers) {
      lines.push(`@\tIN\tNS\t${ns}`);
    }
  }

  for (const record of sorted) {
    lines.push(formatRecordLine(record, root, ttl));
  }

  lines.push('');
  return lines.join('\n');
}

function triggerDownload(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/** Descarga .txt (Hostinger pide .txt BIND). */
export function downloadBindZoneFile(
  apex: string,
  records: ZoneDnsRecord[],
  opts?: BindZoneOptions & { filename?: string },
): void {
  const root = apex.replace(/\.$/, '');
  const content = buildBindZoneFile(apex, records, opts);
  // Sin espacios en el nombre: Windows añade " (1)" y confunde.
  triggerDownload(content, opts?.filename ?? `${root}-matumailer-dns.txt`);
}

export async function copyBindZoneFile(
  apex: string,
  records: ZoneDnsRecord[],
  opts?: BindZoneOptions,
): Promise<void> {
  const content = buildBindZoneFile(apex, records, opts);
  await navigator.clipboard.writeText(content);
}
